runtime: python
env: flex
entrypoint: gunicorn -b :$PORT ingestapp:app
service: chicago
manual_scaling:
  instances: 1

#[START env]
env_variables:
    CLOUD_STORAGE_BUCKET: chicagodemoei-ml
#[END env]

handlers:
- url: /ingest
  script: ingestapp.app

- url: /.*
  script: ingestapp.app
